"use client";

import { useState } from "react";

interface Crawler {
  name: string;
  userAgent: string;
  category: "ai" | "search" | "seo";
  allowed: boolean;
}

const defaultCrawlers: Crawler[] = [
  { name: "GPTBot (OpenAI)", userAgent: "GPTBot", category: "ai", allowed: true },
  { name: "ChatGPT-User", userAgent: "ChatGPT-User", category: "ai", allowed: true },
  { name: "ClaudeBot (Anthropic)", userAgent: "ClaudeBot", category: "ai", allowed: true },
  { name: "Claude-Web", userAgent: "Claude-Web", category: "ai", allowed: true },
  { name: "Google-Extended (Gemini)", userAgent: "Google-Extended", category: "ai", allowed: true },
  { name: "PerplexityBot", userAgent: "PerplexityBot", category: "ai", allowed: true },
  { name: "CCBot (Common Crawl)", userAgent: "CCBot", category: "ai", allowed: true },
  { name: "Bytespider (ByteDance)", userAgent: "Bytespider", category: "ai", allowed: true },
  { name: "Applebot-Extended", userAgent: "Applebot-Extended", category: "ai", allowed: true },
  { name: "Amazonbot", userAgent: "Amazonbot", category: "ai", allowed: true },
  { name: "cohere-ai", userAgent: "cohere-ai", category: "ai", allowed: true },
  { name: "Googlebot", userAgent: "Googlebot", category: "search", allowed: true },
  { name: "Bingbot", userAgent: "Bingbot", category: "search", allowed: true },
  { name: "DuckDuckBot", userAgent: "DuckDuckBot", category: "search", allowed: true },
  { name: "YandexBot", userAgent: "YandexBot", category: "search", allowed: true },
  { name: "Baiduspider", userAgent: "Baiduspider", category: "search", allowed: true },
  { name: "AhrefsBot", userAgent: "AhrefsBot", category: "seo", allowed: true },
  { name: "SemrushBot", userAgent: "SemrushBot", category: "seo", allowed: true },
];

const presets: Record<string, string> = {
  allowAll: "Allow all crawlers",
  blockAll: "Block all crawlers",
  blockAI: "Block AI training, allow search",
  custom: "Custom",
};

function generateRobotsTxt(
  crawlers: Crawler[],
  sitemapUrl: string,
  customPaths: string
): string {
  let output = "# robots.txt generated by GEOKit\n";
  output += `# ${new Date().toISOString().split("T")[0]}\n\n`;

  const blocked = crawlers.filter((c) => !c.allowed);
  const allowed = crawlers.filter((c) => c.allowed);

  if (blocked.length === 0) {
    output += "User-agent: *\nAllow: /\n\n";
  } else {
    const allBlocked = blocked.length === crawlers.length;
    if (allBlocked) {
      output += "User-agent: *\nDisallow: /\n\n";
    } else {
      for (const c of blocked) {
        output += `User-agent: ${c.userAgent}\nDisallow: /\n\n`;
      }
      output += "User-agent: *\nAllow: /\n\n";
    }
  }

  if (customPaths.trim()) {
    output += customPaths.trim() + "\n\n";
  }

  if (sitemapUrl) {
    output += `Sitemap: ${sitemapUrl}\n`;
  }

  return output.trim() + "\n";
}

export default function AiRobotsTxtPage() {
  const [crawlers, setCrawlers] = useState<Crawler[]>(defaultCrawlers);
  const [sitemapUrl, setSitemapUrl] = useState("");
  const [customPaths, setCustomPaths] = useState("");
  const [preset, setPreset] = useState<string>("allowAll");
  const [copied, setCopied] = useState(false);

  const applyPreset = (p: string) => {
    setPreset(p);
    if (p === "allowAll") {
      setCrawlers(defaultCrawlers.map((c) => ({ ...c, allowed: true })));
    } else if (p === "blockAll") {
      setCrawlers(defaultCrawlers.map((c) => ({ ...c, allowed: false })));
    } else if (p === "blockAI") {
      setCrawlers(
        defaultCrawlers.map((c) => ({
          ...c,
          allowed: c.category !== "ai",
        }))
      );
    }
  };

  const toggleCrawler = (userAgent: string) => {
    setPreset("custom");
    setCrawlers(
      crawlers.map((c) =>
        c.userAgent === userAgent ? { ...c, allowed: !c.allowed } : c
      )
    );
  };

  const output = generateRobotsTxt(crawlers, sitemapUrl, customPaths);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "robots.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const categories = [
    { key: "ai" as const, label: "AI Crawlers", color: "text-brand-400" },
    { key: "search" as const, label: "Search Engines", color: "text-green-400" },
    { key: "seo" as const, label: "SEO Bots", color: "text-yellow-400" },
  ];

  return (
    <div className="mx-auto max-w-6xl px-4 py-12">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-3">
          AI Robots.txt Generator
        </h1>
        <p className="text-gray-400">
          Control which AI crawlers (GPTBot, ClaudeBot, PerplexityBot) can
          access your site. Generate a production-ready robots.txt in seconds.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Preset
            </label>
            <select
              value={preset}
              onChange={(e) => applyPreset(e.target.value)}
              className="input-field"
            >
              {Object.entries(presets).map(([key, label]) => (
                <option key={key} value={key} className="bg-gray-800">
                  {label}
                </option>
              ))}
            </select>
          </div>

          {categories.map((cat) => (
            <div key={cat.key}>
              <h3 className={`text-sm font-medium mb-3 ${cat.color}`}>
                {cat.label}
              </h3>
              <div className="space-y-2">
                {crawlers
                  .filter((c) => c.category === cat.key)
                  .map((crawler) => (
                    <label
                      key={crawler.userAgent}
                      className="flex items-center justify-between rounded-lg border border-gray-800 bg-gray-900/50 px-4 py-2.5 cursor-pointer hover:border-gray-700"
                    >
                      <span className="text-sm text-gray-300">
                        {crawler.name}
                      </span>
                      <button
                        onClick={() => toggleCrawler(crawler.userAgent)}
                        className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                          crawler.allowed
                            ? "bg-brand-600"
                            : "bg-gray-700"
                        }`}
                      >
                        <span
                          className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                            crawler.allowed ? "translate-x-6" : "translate-x-1"
                          }`}
                        />
                      </button>
                    </label>
                  ))}
              </div>
            </div>
          ))}

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Sitemap URL (optional)
            </label>
            <input
              type="text"
              value={sitemapUrl}
              onChange={(e) => setSitemapUrl(e.target.value)}
              placeholder="https://yoursite.com/sitemap.xml"
              className="input-field"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Custom Rules (optional)
            </label>
            <textarea
              value={customPaths}
              onChange={(e) => setCustomPaths(e.target.value)}
              placeholder={"Disallow: /admin/\nDisallow: /api/\nDisallow: /private/"}
              rows={4}
              className="input-field font-mono text-sm"
            />
          </div>
        </div>

        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-medium text-gray-300">Preview</h3>
            <div className="flex gap-2">
              <button
                onClick={copyToClipboard}
                className="btn-secondary text-sm py-1.5 px-3"
              >
                {copied ? "✓ Copied!" : "Copy"}
              </button>
              <button
                onClick={download}
                className="btn-primary text-sm py-1.5 px-3"
              >
                Download
              </button>
            </div>
          </div>
          <pre className="code-block min-h-[400px] whitespace-pre-wrap">
            {output}
          </pre>
          <div className="rounded-lg border border-gray-800 bg-gray-900/50 p-4 text-sm text-gray-400">
            <p className="mb-2 font-medium text-gray-300">How to deploy:</p>
            <ol className="list-decimal list-inside space-y-1">
              <li>Download as <code className="text-brand-400">robots.txt</code></li>
              <li>Upload to your website root directory</li>
              <li>Verify at <code className="text-brand-400">yoursite.com/robots.txt</code></li>
              <li>Test with Google Search Console</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  );
}
