"use client";

import { useState } from "react";
import { useLanguage } from "@/components/i18n";

interface LinkItem {
  title: string;
  url: string;
  note: string;
}

interface Section {
  id: string;
  heading: string;
  links: LinkItem[];
}

type Mode = "manual" | "auto";

function generateLlmsTxt(
  title: string,
  summary: string,
  sections: Section[]
): string {
  let output = `# ${title}\n\n`;
  if (summary) {
    output += `> ${summary}\n\n`;
  }
  for (const section of sections) {
    if (section.heading) {
      output += `## ${section.heading}\n\n`;
    }
    for (const link of section.links) {
      if (link.url) {
        const note = link.note ? `: ${link.note}` : "";
        output += `- [${link.title || link.url}](${link.url})${note}\n`;
      }
    }
    output += "\n";
  }
  return output.trim() + "\n";
}

export default function LlmsTxtGeneratorPage() {
  const { t } = useLanguage();
  const [mode, setMode] = useState<Mode>("auto");
  const [title, setTitle] = useState("");
  const [summary, setSummary] = useState("");
  const [sections, setSections] = useState<Section[]>([
    {
      id: "1",
      heading: "",
      links: [{ title: "", url: "", note: "" }],
    },
  ]);
  const [copied, setCopied] = useState(false);

  // Auto mode state
  const [autoUrl, setAutoUrl] = useState("");
  const [autoLoading, setAutoLoading] = useState(false);
  const [autoError, setAutoError] = useState("");
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [generateFull, setGenerateFull] = useState(false);
  const [fullContent, setFullContent] = useState("");
  const [activeTab, setActiveTab] = useState<"standard" | "full">("standard");

  // Advanced Scraping Settings
  const [stripHeader, setStripHeader] = useState(true);
  const [stripFooter, setStripFooter] = useState(true);
  const [stripSidebar, setStripSidebar] = useState(true);
  const [maxWords, setMaxWords] = useState(1000);
  const [showSettings, setShowSettings] = useState(false);

  // AI Summarization Settings
  const [apiProvider, setApiProvider] = useState<"gemini" | "openai" | "deepseek">("gemini");
  const [apiKey, setApiKey] = useState("");
  const [isAiSummarizing, setIsAiSummarizing] = useState(false);
  const [aiError, setAiError] = useState("");
  const [aiSuccess, setAiSuccess] = useState("");

  const standardOutput = generateLlmsTxt(title, summary, sections);
  const output = activeTab === "standard" ? standardOutput : fullContent;

  const addSection = () => {
    setSections([
      ...sections,
      { id: Date.now().toString(), heading: "", links: [{ title: "", url: "", note: "" }] },
    ]);
  };

  const removeSection = (id: string) => {
    setSections(sections.filter((s) => s.id !== id));
  };

  const updateSection = (id: string, heading: string) => {
    setSections(sections.map((s) => (s.id === id ? { ...s, heading } : s)));
  };

  const addLink = (sectionId: string) => {
    setSections(
      sections.map((s) =>
        s.id === sectionId
          ? { ...s, links: [...s.links, { title: "", url: "", note: "" }] }
          : s
      )
    );
  };

  const removeLink = (sectionId: string, index: number) => {
    setSections(
      sections.map((s) =>
        s.id === sectionId
          ? { ...s, links: s.links.filter((_, i) => i !== index) }
          : s
      )
    );
  };

  const updateLink = (
    sectionId: string,
    index: number,
    field: keyof LinkItem,
    value: string
  ) => {
    setSections(
      sections.map((s) =>
        s.id === sectionId
          ? {
              ...s,
              links: s.links.map((l, i) =>
                i === index ? { ...l, [field]: value } : l
              ),
            }
          : s
      )
    );
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = activeTab === "standard" ? "llms.txt" : "llms-full.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const fetchFromUrl = async () => {
    if (!autoUrl.trim()) return;
    setAutoLoading(true);
    setAutoError("");
    setAutoGenerated(false);
    setFullContent("");
    setActiveTab("standard");
    try {
      const res = await fetch("/api/fetch-sitemap", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: autoUrl }),
      });
      const data = await res.json();
      if (!res.ok) {
        setAutoError(data.error || "Failed to fetch site data");
        return;
      }
      // Populate the form with fetched data
      setTitle(data.title || "");
      setSummary(data.description || "");
      let fetchedUrls: string[] = [];
      if (data.sections && data.sections.length > 0) {
        setSections(
          data.sections.map((s: { heading: string; links: LinkItem[] }, i: number) => ({
            id: `auto-${i}`,
            heading: s.heading,
            links: s.links.map((l: LinkItem) => {
              if (l.url) fetchedUrls.push(l.url);
              return {
                title: l.title || "",
                url: l.url || "",
                note: l.note || "",
              };
            }),
          }))
        );
      }
      setAutoGenerated(true);

      // If full mode is requested, fetch content for all pages with custom filters
      if (generateFull && fetchedUrls.length > 0) {
        const fullRes = await fetch("/api/fetch-full-content", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            urls: fetchedUrls,
            stripHeader,
            stripFooter,
            stripSidebar,
            maxWords,
          }),
        });
        const fullData = await fullRes.json();
        if (fullRes.ok) {
          setFullContent(fullData.content);
          setActiveTab("full");
        } else {
          setAutoError(`Standard llms.txt generated, but full content crawl failed: ${fullData.error}`);
        }
      }
    } catch {
      setAutoError("Network error. Please check the URL and try again.");
    } finally {
      setAutoLoading(false);
    }
  };

  // Client-Side AI Summarizer call
  const generateAiSummaries = async () => {
    if (!apiKey.trim()) {
      setAiError("Please enter your API Key first.");
      return;
    }
    setIsAiSummarizing(true);
    setAiError("");
    setAiSuccess("");

    try {
      const allLinks = sections.flatMap((s) => s.links.map((l) => ({ link: l, sectionId: s.id })));
      const activeLinks = allLinks.filter((al) => al.link.url.trim().length > 0);

      if (activeLinks.length === 0) {
        setAiError("No active page links to summarize. Run crawl first.");
        setIsAiSummarizing(false);
        return;
      }

      // Summarize in parallel batches of 3
      for (let i = 0; i < activeLinks.length; i += 3) {
        const batch = activeLinks.slice(i, i + 3);
        await Promise.all(
          batch.map(async ({ link, sectionId }, idx) => {
            const context = link.note || link.title || "Page Content";
            let summaryText = "";

            if (apiProvider === "gemini") {
              const res = await fetch(
                `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
                {
                  method: "POST",
                  headers: { "Content-Type": "application/json" },
                  body: JSON.stringify({
                    contents: [
                      {
                        parts: [
                          {
                            text: `Write a high-density, professional 1-sentence note for an llms.txt file summarizing this webpage: Title is "${link.title}" and context info is "${context}". Do not prefix with 'this page' or 'summary', write the direct content value. Max 60 tokens.`,
                          },
                        ],
                      },
                    ],
                    generationConfig: { maxOutputTokens: 60, temperature: 0.3 },
                  }),
                }
              );
              const data = await res.json();
              summaryText = data?.candidates?.[0]?.content?.parts?.[0]?.text || "";
            } else if (apiProvider === "openai" || apiProvider === "deepseek") {
              const url =
                apiProvider === "openai"
                  ? "https://api.openai.com/v1/chat/completions"
                  : "https://api.deepseek.com/v1/chat/completions";
              const model = apiProvider === "openai" ? "gpt-4o-mini" : "deepseek-chat";
              const res = await fetch(url, {
                method: "POST",
                headers: {
                  "Content-Type": "application/json",
                  Authorization: `Bearer ${apiKey}`,
                },
                body: JSON.stringify({
                  model,
                  messages: [
                    {
                      role: "user",
                      content: `Write a high-density, professional 1-sentence note for an llms.txt file summarizing this webpage: Title is "${link.title}" and context info is "${context}". Do not prefix with 'this page' or 'summary', write the direct content value. Max 60 tokens.`,
                    },
                  ],
                  max_tokens: 60,
                  temperature: 0.3,
                }),
              });
              const data = await res.json();
              summaryText = data?.choices?.[0]?.message?.content || "";
            }

            summaryText = summaryText.trim().replace(/^["']|["']$/g, "");
            if (summaryText) {
              // Update state link note dynamically
              setSections((prev) =>
                prev.map((s) => {
                  if (s.id !== sectionId) return s;
                  return {
                    ...s,
                    links: s.links.map((l) => (l.url === link.url ? { ...l, note: summaryText } : l)),
                  };
                })
              );
            }
          })
        );
      }
      setAiSuccess("Successfully generated professional notes using AI for all pages!");
    } catch (err) {
      setAiError(`AI Request failed: ${(err as Error).message || "Check your API Key or Network"}`);
    } finally {
      setIsAiSummarizing(false);
    }
  };

  return (
    <div className="mx-auto max-w-6xl px-4 py-12">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-3">
          {t("llms.txt Generator", "llms.txt Generator")}
        </h1>
        <p className="text-gray-400">
          Create an llms.txt file that tells AI models what your site is about
          and which pages matter most. Deploy to your site root as{" "}
          <code className="text-brand-400">/llms.txt</code>.
        </p>
      </div>

      {/* Mode Toggle */}
      <div className="flex gap-1 rounded-lg border border-gray-800 bg-gray-900/50 p-1 mb-8 w-fit">
        <button
          onClick={() => setMode("auto")}
          className={`rounded-md px-4 py-2 text-sm font-medium transition-colors ${
            mode === "auto"
              ? "bg-brand-500 text-white"
              : "text-gray-400 hover:text-white"
          }`}
        >
          {t("🔗 Auto from URL", "🔗 Auto from URL")}
        </button>
        <button
          onClick={() => setMode("manual")}
          className={`rounded-md px-4 py-2 text-sm font-medium transition-colors ${
            mode === "manual"
              ? "bg-brand-500 text-white"
              : "text-gray-400 hover:text-white"
          }`}
        >
          {t("✏️ Manual", "✏️ Manual")}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Form */}
        <div className="space-y-6">
          {/* Auto URL input */}
          {mode === "auto" && (
            <div className="rounded-lg border border-brand-500/30 bg-brand-500/5 p-4 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Website URL
                </label>
                <div className="flex gap-3">
                  <input
                    type="text"
                    value={autoUrl}
                    onChange={(e) => setAutoUrl(e.target.value)}
                    onKeyDown={(e) => e.key === "Enter" && fetchFromUrl()}
                    placeholder="https://yoursite.com"
                    className="input-field flex-1"
                  />
                  <button
                    onClick={fetchFromUrl}
                    disabled={autoLoading || !autoUrl.trim()}
                    className="btn-primary whitespace-nowrap disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {autoLoading ? (
                      <span className="flex items-center gap-2">
                        <span className="animate-spin inline-block h-4 w-4 border-2 border-white/30 border-t-white rounded-full" />
                        Crawling...
                      </span>
                    ) : (
                      "Generate →"
                    )}
                  </button>
                </div>
                <p className="text-xs text-gray-500 mt-2">
                  We&apos;ll fetch your sitemap.xml and page titles to auto-generate the file. You can edit everything below.
                </p>
                <div className="flex items-center gap-2 mt-3">
                  <input
                    type="checkbox"
                    id="generateFull"
                    checked={generateFull}
                    onChange={(e) => setGenerateFull(e.target.checked)}
                    className="rounded border-gray-800 bg-gray-900 text-brand-500 focus:ring-brand-500 h-4 w-4"
                  />
                  <label htmlFor="generateFull" className="text-xs text-gray-300 select-none cursor-pointer">
                    Also crawl page content to generate <code className="text-brand-400">llms-full.txt</code> (takes longer)
                  </label>
                </div>
              </div>

              {/* Collapsible Scraping Settings */}
              <div className="border-t border-gray-800/80 pt-3">
                <button
                  onClick={() => setShowSettings(!showSettings)}
                  className="text-xs text-gray-400 hover:text-white flex items-center gap-1 font-medium transition-colors"
                >
                  ⚙️ {showSettings ? "Hide Advanced Scraping Settings" : "Show Advanced Scraping Settings"}
                </button>

                {showSettings && (
                  <div className="mt-3 p-3 rounded-lg bg-gray-950/60 border border-gray-800/80 grid grid-cols-1 sm:grid-cols-2 gap-3 animate-fade-in">
                    <div className="space-y-2">
                      <div className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          id="stripHeader"
                          checked={stripHeader}
                          onChange={(e) => setStripHeader(e.target.checked)}
                          className="rounded border-gray-700 bg-gray-900 text-brand-500 h-4.5 w-4.5"
                        />
                        <label htmlFor="stripHeader" className="text-xs text-gray-300 select-none cursor-pointer">
                          Strip headers &amp; navs
                        </label>
                      </div>
                      <div className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          id="stripFooter"
                          checked={stripFooter}
                          onChange={(e) => setStripFooter(e.target.checked)}
                          className="rounded border-gray-700 bg-gray-900 text-brand-500 h-4.5 w-4.5"
                        />
                        <label htmlFor="stripFooter" className="text-xs text-gray-300 select-none cursor-pointer">
                          Strip footers
                        </label>
                      </div>
                      <div className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          id="stripSidebar"
                          checked={stripSidebar}
                          onChange={(e) => setStripSidebar(e.target.checked)}
                          className="rounded border-gray-700 bg-gray-900 text-brand-500 h-4.5 w-4.5"
                        />
                        <label htmlFor="stripSidebar" className="text-xs text-gray-300 select-none cursor-pointer">
                          Strip sidebars
                        </label>
                      </div>
                    </div>
                    <div>
                      <label className="block text-xs text-gray-400 mb-1">Max Words Per Page</label>
                      <select
                        value={maxWords}
                        onChange={(e) => setMaxWords(Number(e.target.value))}
                        className="input-field py-1 text-xs"
                      >
                        <option value={500}>500 words</option>
                        <option value={1000}>1000 words</option>
                        <option value={2000}>2000 words</option>
                        <option value={3000}>3000 words</option>
                      </select>
                    </div>
                  </div>
                )}
              </div>

              {autoError && (
                <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-red-400 text-sm">
                  {autoError}
                </div>
              )}

              {autoGenerated && (
                <div className="rounded-lg border border-green-500/30 bg-green-500/10 p-3 text-green-400 text-sm flex items-center gap-2">
                  <span>✓</span>
                  <span>Successfully generated from sitemap! Review and edit below, then download.</span>
                </div>
              )}
            </div>
          )}

          {/* AI Notes Auto-enrich Config */}
          {autoGenerated && (
            <div className="rounded-lg border border-brand-500/30 bg-gray-900/40 p-4 space-y-3">
              <h4 className="text-sm font-semibold text-white flex items-center gap-1.5">
                <span>🤖</span> AI Note Auto-Enrichment
              </h4>
              <p className="text-xs text-gray-400 leading-relaxed">
                Generate professional, high-density 1-sentence summaries for all page notes dynamically using your own LLM API Key (100% private).
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-[11px] text-gray-400 mb-1">API Provider</label>
                  <select
                    value={apiProvider}
                    onChange={(e) => setApiProvider(e.target.value as any)}
                    className="input-field py-1.5 text-xs"
                  >
                    <option value="gemini">Google Gemini (1.5 Flash)</option>
                    <option value="openai">OpenAI (GPT-4o Mini)</option>
                    <option value="deepseek">DeepSeek (deepseek-chat)</option>
                  </select>
                </div>
                <div>
                  <label className="block text-[11px] text-gray-400 mb-1">API Key</label>
                  <input
                    type="password"
                    value={apiKey}
                    onChange={(e) => setApiKey(e.target.value)}
                    placeholder="Paste your API Key"
                    className="input-field py-1.5 text-xs"
                  />
                </div>
              </div>
              <div className="flex justify-end pt-1">
                <button
                  onClick={generateAiSummaries}
                  disabled={isAiSummarizing || !apiKey.trim()}
                  className="btn-primary text-xs py-1.5 px-4 disabled:opacity-50"
                >
                  {isAiSummarizing ? "AI Summarizing..." : "⚡ Enrich notes with AI"}
                </button>
              </div>

              {aiError && (
                <div className="text-xs text-red-400 bg-red-500/10 border border-red-500/30 p-2.5 rounded-lg">
                  {aiError}
                </div>
              )}
              {aiSuccess && (
                <div className="text-xs text-green-400 bg-green-500/10 border border-green-500/30 p-2.5 rounded-lg">
                  {aiSuccess}
                </div>
              )}
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Site Title (H1) *
            </label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Acme — AI-Powered Project Management"
              className="input-field"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Summary
            </label>
            <textarea
              value={summary}
              onChange={(e) => setSummary(e.target.value)}
              placeholder="A one-sentence description of your site for AI models to understand your content."
              rows={2}
              className="input-field"
            />
          </div>

          {sections.map((section, sIdx) => (
            <div
              key={section.id}
              className="rounded-lg border border-gray-800 bg-gray-900/50 p-4 space-y-4"
            >
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium text-gray-400">
                  Section {sIdx + 1}
                </span>
                {sections.length > 1 && (
                  <button
                    onClick={() => removeSection(section.id)}
                    className="text-xs text-red-400 hover:text-red-300"
                  >
                    Remove section
                  </button>
                )}
              </div>
              <input
                type="text"
                value={section.heading}
                onChange={(e) => updateSection(section.id, e.target.value)}
                placeholder="Section heading (e.g. Docs, API, Blog)"
                className="input-field"
              />
              {section.links.map((link, lIdx) => (
                <div key={lIdx} className="space-y-2 pl-4 border-l border-gray-800">
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-gray-500">Link {lIdx + 1}</span>
                    {section.links.length > 1 && (
                      <button
                        onClick={() => removeLink(section.id, lIdx)}
                        className="text-xs text-red-400 hover:text-red-300"
                      >
                        Remove
                      </button>
                    )}
                  </div>
                  <input
                    type="text"
                    value={link.title}
                    onChange={(e) =>
                      updateLink(section.id, lIdx, "title", e.target.value)
                    }
                    placeholder="Link title (e.g. Getting Started)"
                    className="input-field text-sm"
                  />
                  <input
                    type="text"
                    value={link.url}
                    onChange={(e) =>
                      updateLink(section.id, lIdx, "url", e.target.value)
                    }
                    placeholder="URL (e.g. https://acme.com/docs)"
                    className="input-field text-sm"
                  />
                  <input
                    type="text"
                    value={link.note}
                    onChange={(e) =>
                      updateLink(section.id, lIdx, "note", e.target.value)
                    }
                    placeholder="Optional note (e.g. Quick start guide)"
                    className="input-field text-sm"
                  />
                </div>
              ))}
              <button
                onClick={() => addLink(section.id)}
                className="text-sm text-brand-400 hover:text-brand-300"
              >
                + Add link
              </button>
            </div>
          ))}

          <button
            onClick={addSection}
            className="btn-secondary w-full"
          >
            + Add Section
          </button>
        </div>

        {/* Preview */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex gap-2">
              <button
                onClick={() => setActiveTab("standard")}
                className={`text-sm font-medium px-3 py-1.5 rounded-md transition-colors ${
                  activeTab === "standard"
                    ? "bg-brand-500/10 border border-brand-500/30 text-white"
                    : "text-gray-400 hover:text-white"
                }`}
              >
                Standard (llms.txt)
              </button>
              {fullContent && (
                <button
                  onClick={() => setActiveTab("full")}
                  className={`text-sm font-medium px-3 py-1.5 rounded-md transition-colors ${
                    activeTab === "full"
                      ? "bg-brand-500/10 border border-brand-500/30 text-white"
                      : "text-gray-400 hover:text-white"
                  }`}
                >
                  Full (llms-full.txt)
                </button>
              )}
            </div>
            <div className="flex gap-2">
              <button
                onClick={copyToClipboard}
                className="btn-secondary text-sm py-1.5 px-3"
              >
                {copied ? "✓ Copied!" : "Copy"}
              </button>
              <button
                onClick={download}
                className="btn-primary text-sm py-1.5 px-3"
              >
                Download
              </button>
            </div>
          </div>
          <pre className="code-block min-h-[400px] whitespace-pre-wrap">
            {output || (activeTab === "standard" ? "# Your llms.txt will appear here" : "# Your llms-full.txt will appear here")}
          </pre>
          <div className="rounded-lg border border-gray-800 bg-gray-900/50 p-4 text-sm text-gray-400">
            <p className="mb-2 font-medium text-gray-300">How to deploy:</p>
            <ol className="list-decimal list-inside space-y-1">
              <li>Download the file as <code className="text-brand-400">{activeTab === "standard" ? "llms.txt" : "llms-full.txt"}</code></li>
              <li>Upload to your website root directory</li>
              <li>Make sure it&apos;s accessible at <code className="text-brand-400">yoursite.com/{activeTab === "standard" ? "llms.txt" : "llms-full.txt"}</code></li>
              {activeTab === "standard" && (
                <li>Validate it with our <a href="/tools/llms-txt-validator" className="text-brand-400 hover:underline">llms.txt Validator</a></li>
              )}
            </ol>
          </div>
        </div>
      </div>
    </div>
  );
}
